### ISSUE TITLE
TypeError: _stack_dispatcher() got an unexpected keyword argument 'dtype'

### ISSUE THREAD

**Issue by ShmuelRonen** [CY-CHENYUE/ComfyUI-Molmo#14]
got prompt
Loading model from /home/sam/ComfyUI/models/Molmo/molmo-7B-D-bnb-4bit
Unused kwargs: ['_load_in_4bit', '_load_in_8bit', 'quant_method']. These kwargs are not used in <class 'transformers.utils.quantization_config.BitsAndBytesConfig'>.
We will use 90% of the memory on device 0 for storing the model, and 10% for the buffer to avoid OOM. You can set `max_memory` in to a higher value to use more memory (at your own risk).
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.39s/it]
Model and processor have been unloaded, and CUDA cache has been cleared.
!!! Exception during processing !!! _stack_dispatcher() got an unexpected keyword argument 'dtype'
Traceback (most recent call last):
  File "/home/sam/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/sam/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/sam/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/sam/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/sam/ComfyUI/custom_nodes/ComfyUI-Molmo/Molmo7BDbnb.py", line 170, in generate_caption
    inputs = self.processor.process(
  File "/home/sam/.cache/huggingface/modules/transformers_modules/molmo-7B-D-bnb-4bit/preprocessing_molmo.py", line 145, in process
    out = self.image_processor.multimodal_preprocess(
  File "/home/sam/.cache/huggingface/modules/transformers_modules/molmo-7B-D-bnb-4bit/image_preprocessing_molmo.py", line 525, in multimodal_preprocess
    crops, image_tokens, patch_idx, img_mask = self.preprocess(
  File "/home/sam/.cache/huggingface/modules/transformers_modules/molmo-7B-D-bnb-4bit/image_preprocessing_molmo.py", line 450, in preprocess
    crops, image_tokens, patch_ordering, img_mask = self.image_to_patches_and_tokens(
  File "/home/sam/.cache/huggingface/modules/transformers_modules/molmo-7B-D-bnb-4bit/image_preprocessing_molmo.py", line 235, in image_to_patches_and_tokens
    tiling = select_tiling(
  File "/home/sam/.cache/huggingface/modules/transformers_modules/molmo-7B-D-bnb-4bit/image_preprocessing_molmo.py", line 138, in select_tiling
    original_size = np.stack([h, w], dtype=np.float32)  # [1, 2]
  File "<__array_function__ internals>", line 179, in stack
TypeError: _stack_dispatcher() got an unexpected keyword argument 'dtype'

_____________

My ComfyUI :

** Platform: Linux
** Python version: 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
** Python executable: /home/sam/ComfyUI/venv/bin/python
** ComfyUI Path: /home/sam/ComfyUI
** Log path: /home/sam/ComfyUI/comfyui.log

Total VRAM 24576 MB, total RAM 31689 MB
pytorch version: 2.4.1+cu121
xformers version: 0.0.28.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using xformers cross attention

**Comment by ShmuelRonen** [comment]
Find a solution 👍 
pip install numpy==1.24.4
