### ISSUE TITLE
OOM 问题

### ISSUE THREAD

**Issue by weeming21** [CY-CHENYUE/ComfyUI-Molmo#23]
我显卡RTX4090 oc, 24G显存
全新安装的comfyui, workflow只调用3个node：
load image->molmo ->show any
未按prompt前，显存用了5%，按prompt后，执行到molmo部分，会慢慢跳满100%
然后就报错OOM，不能进入下一给node，同时显存就被占用63%不会被释放，必须restart才会归5%

2024-11-24T16:04:13.860430 - Loading model from /home/comfyui/comfyui/ComfyUI/models/Molmo/molmo-7B-D-bnb-4bit2024-11-24T16:04:13.860448 - 
2024-11-24T16:04:14.209000 - Unused kwargs: ['_load_in_4bit', '_load_in_8bit', 'quant_method']. These kwargs are not used in <class 'transformers.utils.quantization_config.BitsAndBytesConfig'>.
2024-11-24T16:04:14.569120 - We will use 90% of the memory on device 0 for storing the model, and 10% for the buffer to avoid OOM. You can set `max_memory` in to a higher value to use more memory (at your own risk).
2024-11-24T16:04:16.159306 - 
Loading checkpoint shards: 100%|██████████| 2/2 [00:01<00:00,  1.38it/s]2024-11-24T16:04:16.159404 - 
Loading checkpoint shards: 100%|██████████| 2/2 [00:01<00:00,  1.32it/s]2024-11-24T16:04:16.159415 - 
2024-11-24T16:04:17.070268 - Model and processor have been unloaded, and CUDA cache has been cleared.2024-11-24T16:04:17.070289 - 
2024-11-24T16:04:17.072117 - !!! Exception during processing !!! Allocation on device 
2024-11-24T16:04:17.073352 - Traceback (most recent call last):
  File "/home/comfyui/comfyui/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/comfyui/comfyui/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/comfyui/comfyui/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/comfyui/comfyui/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/comfyui/comfyui/ComfyUI/custom_nodes/ComfyUI-Molmo/Molmo7BDbnb.py", line 191, in generate_caption
    output = self.model.generate_from_batch(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/comfyui/.local/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/comfyui/.cache/huggingface/modules/transformers_modules/molmo-7B-D-bnb-4bit/modeling_molmo.py", line 2466, in generate_from_batch
    out = super().generate(
          ^^^^^^^^^^^^^^^^^
  File "/home/comfyui/.local/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/comfyui/.local/lib/python3.12/site-packages/transformers/generation/utils.py", line 2215, in generate
    result = self._sample(
             ^^^^^^^^^^^^^
  File "/home/comfyui/.local/lib/python3.12/site-packages/transformers/generation/utils.py", line 3206, in _sample
    outputs = self(**model_inputs, return_dict=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/comfyui/.local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/comfyui/.local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/comfyui/.local/lib/python3.12/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/comfyui/.cache/huggingface/modules/transformers_modules/molmo-7B-D-bnb-4bit/modeling_molmo.py", line 2360, in forward
    outputs = self.model.forward(
              ^^^^^^^^^^^^^^^^^^^
  File "/home/comfyui/.local/lib/python3.12/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/comfyui/.cache/huggingface/modules/transformers_modules/molmo-7B-D-bnb-4bit/modeling_molmo.py", line 2085, in forward
    x = self.transformer.wte(input_ids) if input_embeddings is None else input_embeddings  # type: ignore
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/comfyui/.local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/comfyui/.local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/comfyui/.local/lib/python3.12/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/comfyui/.cache/huggingface/modules/transformers_modules/molmo-7B-D-bnb-4bit/modeling_molmo.py", line 745, in forward
    return F.embedding(x, torch.cat([self.embedding, self.new_embedding], dim=0))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: Allocation on device

**Comment by Yuqi2347** [comment]
解决了吗，遇到同样的问题

**Comment by MoonChild2121** [comment]
> Have you solved it? I have the same problem.

Have you been able to solve it?

**Comment by MoonChild2121** [comment]
> Have you solved it? I have the same problem.

Have you been able to solve it?
